LodiCornFest5k/Controllers/ResultsController.cs
using LodiCornFest5k.Data;
using LodiCornFest5k.ViewModels;
using LodiCornFest5k.ViewModels.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LodiCornFest5k.Controllers
{
    public class ResultsController : Controller
    {
        private readonly RaceContext context;

        public ResultsController(RaceContext context)
        {
            this.context = context;
        }

        [HttpGet("/results/index")]
        public async Task<IActionResult> Index()
        {
            var viewModel = new IndexViewModel
            {
                Races = await this.context.Races.ToListAsync()
            };

            return View(viewModel);
        }

        [HttpGet("/results/{year}")]
        public async Task<IActionResult> Race(int year)
        {
            var viewModel = new RaceViewModel
            {
                Race = await this.context.Races.SingleAsync(x => x.Date.Year == year)
            };

            return View(viewModel);
        }

        [HttpGet("/results/{year}/list")]
        public async Task<IActionResult> List(int year)
        {
            var race = await this.context.Races
                .Include(x => x.RaceRunners)
                    .ThenInclude(x => x.Runner)
                .Include(x => x.RaceRunners)
                    .ThenInclude(x => x.AgeGroup)
                .FirstAsync(x => x.Date.Year == year);

            var runners = new List<RunnerViewModel>();

            foreach (var raceRunner in race.RaceRunners.OrderBy(x => x.Runner.Gender).ThenBy(x => x.Runner.LastName))
            {
                var runner = new RunnerViewModel
                {
                    Name = $"{raceRunner.Runner.FirstName} {raceRunner.Runner.LastName}",
                    Gender = raceRunner.Runner.Gender,
                    AgeGroupName = raceRunner.AgeGroup.Name
                };

                runners.Add(runner);
            }

            var viewModel = new ListViewModel
            {
                Race = race,
                Runners = runners
            };

            return View(viewModel);
        }

        [HttpGet("/results/{year}/overall")]
        public async Task<IActionResult> Overall(int year)
        {
            var race = await this.context.Races
                .Include(x => x.RaceRunners)
                    .ThenInclude(x => x.Runner)
                .Include(x => x.RaceRunners)
                    .ThenInclude(x => x.AgeGroup)
                .Include(x => x.Results)
                    .ThenInclude(x => x.Runner)
                .FirstAsync(x => x.Date.Year == year);

            
            var results = new List<ResultViewModel>();

            foreach (var dbResult in race.Results.OrderBy(x => x.OverallPlace))
            {
                var ageGroup = race.RaceRunners.First(x => x.RunnerId == dbResult.Runner.Id).AgeGroup;

                var result = new ResultViewModel
                {
                    Place = dbResult.OverallPlace,
                    Name = $"{dbResult.Runner.FirstName} {dbResult.Runner.LastName}",
                    Gender = dbResult.Runner.Gender,
                    AgeGroupName = ageGroup.Name,
                    Time = dbResult.Time,
                    RaceName = race.Name
                };

                results.Add(result);
            }

            var viewModel = new OverallViewModel
            {
                Race = race,
                Results = results
            };

            return View(viewModel);
        }

        [HttpGet("/results/{year}/age")]
        public async Task<IActionResult> AgeGroup(int year)
        {
            var race = await this.context.Races
                .Include(x => x.AgeGroups)
                    .ThenInclude(x => x.Results)
                .Include(x => x.RaceRunners)
                    .ThenInclude(x => x.Runner)
                .Include(x => x.RaceRunners)
                    .ThenInclude(x => x.AgeGroup)
                .Include(x => x.Results)
                    .ThenInclude(x => x.Runner)
                .FirstAsync(x => x.Date.Year == year);

            var ageGroups = new List<AgeGroupResultsViewModel>();

            foreach (var ageGroup in race.AgeGroups)
            {
                var raceRunnerIds = race.RaceRunners.Where(x => x.AgeGroup.Id == ageGroup.Id).Select(x => x.Runner.Id);
                var ageGroupResults = race.Results.Where(x => raceRunnerIds.Contains(x.Runner.Id));

                var results = new List<ResultViewModel>();

                foreach (var ageGroupResult in ageGroupResults)
                {
                    var res = new ResultViewModel
                    {
                        Place = ageGroupResult.AgeGroupPlace,
                        Name = $"{ageGroupResult.Runner.FirstName} {ageGroupResult.Runner.LastName}",
                        Gender = ageGroupResult.Runner.Gender,
                        AgeGroupName = ageGroup.Name,
                        Time = ageGroupResult.Time,
                        RaceName = race.Name
                    };

                    results.Add(res);
                }

                var result = new AgeGroupResultsViewModel
                {
                    Name = ageGroup.Name,
                    Gender = ageGroup.Gender,
                    Results = results.OrderBy(x => x.Place).ToList()
                };

                ageGroups.Add(result);
            }

            var viewModel = new AgeGroupViewModel
            {
                Race = race,
                AgeGroups = ageGroups.OrderBy(x => x.Gender).ThenBy(x => x.Name).ToList()
            };

            return View(viewModel);
        }
    }
}

LodiCornFest5k/Controllers/RouteController.cs
using Microsoft.AspNetCore.Mvc;

namespace LodiCornFest5k.Controllers
{
    public class RouteController : Controller
    {
        [HttpGet("/route/index")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

LodiCornFest5k/Views/Shared/_CoverLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/cover.css" />
    @RenderSection("Styles", false)

    <link rel="apple-touch-icon" sizes="180x180" href="~/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon-16x16.png">
    <link rel="manifest" href="~/site.webmanifest">
    <link rel="mask-icon" href="~/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="~/#da532c">
    <meta name="theme-color" content="#ffffff">
    <title>Lodi Corn Fest 5k</title>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-83190618-3"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-83190618-3');
    </script>
</head>
<body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
            <div class="inner">
                <h3 class="masthead-brand">Lodi Corn Fest 5K</h3>
                <nav class="nav nav-masthead justify-content-center">
                    <a asp-controller="Home" asp-action="Index" is-active-route class="nav-link">Home</a>
                    <a asp-controller="Results" asp-action="Index" is-active-route class="nav-link">Results</a>
                    <a asp-controller="Route" asp-action="Index" is-active-route class="nav-link">Route Map</a>
                </nav>
            </div>
        </header>
        <main role="main" class="inner cover">
            @RenderBody()
        </main>
        <footer class="mastfoot mt-auto">
            <div class="inner">
                <p>LodiCornFest5k.com is made with &#10084; by <a href="https://twitter.com/TonyTalksTech" target="_blank">Tony Morris</a>.
            </div>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    @RenderSection("Scripts", false)
</body>
</html>

LodiCornFest5k/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/sticky-footer.css" />
    @RenderSection("Styles", false)

    <link rel="apple-touch-icon" sizes="180x180" href="~/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon-16x16.png">
    <link rel="manifest" href="~/site.webmanifest">
    <link rel="mask-icon" href="~/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="~/#da532c">
    <meta name="theme-color" content="#ffffff">
    <title>@ViewData["Title"] | Lodi Corn Fest 5k</title>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-83190618-3"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-83190618-3');
    </script>
</head>
<body data-spy="scroll" data-target="#toc">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="/">Lodi Corn Fest 5K</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li asp-controller="Home" asp-action="Index" is-active-route class="nav-item">
                    <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                </li>
                <li asp-controller="Results" asp-action="Index" is-active-route class="nav-item">
                    <a asp-controller="Results" asp-action="Index" class="nav-link">Results</a>
                </li>
                <li asp-controller="Route" asp-action="Index" is-active-route class="nav-item">
                    <a asp-controller="Route" asp-action="Index" class="nav-link">Route Map</a>
                </li>
            </ul>
        </div>
    </nav>
    <main role="main" class="container-fluid">
        @RenderBody()
    </main>
    <footer class="footer">
        <div class="container">
            <span class="text-muted">LodiCornFest5k.com is made with &#10084; by <a href="https://twitter.com/TonyTalksTech" target="_blank">Tony Morris</a></span>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    @RenderSection("Scripts", false)
</body>
</html>