LodiCornFest5k/Models/AgeGroup.cs
using System.Collections.Generic;

namespace LodiCornFest5k.Models
{
    public class AgeGroup
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Gender Gender { get; set; }
        
        public Race Race { get; set; }
        public ICollection<Result> Results { get; set; } = new HashSet<Result>();
    }
}

LodiCornFest5k/Models/Race.cs
using System;
using System.Collections.Generic;

namespace LodiCornFest5k.Models
{
    public class Race
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Date { get; set; }

        public ICollection<AgeGroup> AgeGroups { get; set; } = new HashSet<AgeGroup>();
        public ICollection<RaceRunner> RaceRunners { get; set; } = new HashSet<RaceRunner>();
        public ICollection<Result> Results { get; set; } = new HashSet<Result>();
    }
}

LodiCornFest5k/Models/Result.cs
using System;

namespace LodiCornFest5k.Models
{
    public class Result
    {
        public int Id { get; set; }
        public TimeSpan Time { get; set; }
        public int AgeGroupPlace { get; set; }
        public int OverallPlace { get; set; }

        public Runner Runner { get; set; }
        public Race Race { get; set; }
    }
}

LodiCornFest5k/ViewModels/AgeGroupViewModel.cs
using LodiCornFest5k.Models;
using System.Collections.Generic;

namespace LodiCornFest5k.ViewModels
{
    public class AgeGroupResultsViewModel
    {
        public string Name { get; set; }
        public Gender Gender { get; set; }
        public string Link => $"{this.Gender.ToString()}-{this.Name.Replace(" ", "").Replace("&","and").Replace("+","plus")}";
        public List<ResultViewModel> Results { get; set; } = new List<ResultViewModel>();
    }
}

LodiCornFest5k/ViewModels/ResultViewModel.cs
using LodiCornFest5k.Models;
using System;

namespace LodiCornFest5k.ViewModels
{
    public class ResultViewModel
    {
        public int Place { get; set; }
        public string Name { get; set; }
        public Gender Gender { get; set; }
        public string AgeGroupName { get; set; }
        public TimeSpan Time { get; set; }
        public string RaceName { get; set; }
        public int OverallPlace { get; set; }
        public int AgeGroupPlace { get; set; }
        public int RaceYear { get; set; }

        public string LinkName
        {
            get
            {
                var names = this.Name.ToLower().Split(" ");
                var firstName = names[0];
                var lastName = names[1];

                return $"{firstName}-{lastName}";
            }
        }

        public string AgeGroupLink
        {
            get
            {
                return $"{this.Gender.ToString().ToLower()}-{this.AgeGroupName.Replace(" ", "").Replace("+", "-").Replace("&", "-").ToLower()}";
            }
        }
    }
}

LodiCornFest5k/ViewModels/Results/AgeGroupViewModel.cs
using LodiCornFest5k.Models;
using System.Collections.Generic;

namespace LodiCornFest5k.ViewModels.Results
{
    public class AgeGroupViewModel
    {
        public Race Race { get; set; }
        public List<AgeGroupResultsViewModel> AgeGroups { get; set; } = new List<AgeGroupResultsViewModel>();
    }
}

LodiCornFest5k/ViewModels/Results/IndexViewModel.cs
using LodiCornFest5k.Models;
using System.Collections.Generic;

namespace LodiCornFest5k.ViewModels.Results
{
    public class IndexViewModel
    {
        public ICollection<Race> Races { get; set; } = new HashSet<Race>();
    }
}

LodiCornFest5k/ViewModels/Results/ListViewModel.cs
using LodiCornFest5k.Models;
using System.Collections.Generic;

namespace LodiCornFest5k.ViewModels.Results
{
    public class ListViewModel
    {
        public Race Race { get; set; }
        public List<RunnerViewModel> Runners { get; set; } = new List<RunnerViewModel>();
    }
}

LodiCornFest5k/ViewModels/Results/OverallViewModel.cs
using LodiCornFest5k.Models;
using System.Collections.Generic;

namespace LodiCornFest5k.ViewModels.Results
{
    public class OverallViewModel
    {
        public Race Race { get; set; }
        public List<ResultViewModel> Results { get; set; } = new List<ResultViewModel>();
    }
}

LodiCornFest5k/ViewModels/Results/RaceViewModel.cs
using LodiCornFest5k.Models;

namespace LodiCornFest5k.ViewModels.Results
{
    public class RaceViewModel
    {
        public Race Race { get; set; }
    }
}

LodiCornFest5k/Controllers/ResultsController.cs
using LodiCornFest5k.Data;
using LodiCornFest5k.ViewModels;
using LodiCornFest5k.ViewModels.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LodiCornFest5k.Controllers
{
    public class ResultsController : Controller
    {
        private readonly RaceContext context;

        public ResultsController(RaceContext context)
        {
            this.context = context;
        }

        [HttpGet("/results/index")]
        public async Task<IActionResult> Index()
        {
            var viewModel = new IndexViewModel
            {
                Races = await this.context.Races.ToListAsync()
            };

            return View(viewModel);
        }

        [HttpGet("/results/{year}")]
        public async Task<IActionResult> Race(int year)
        {
            var viewModel = new RaceViewModel
            {
                Race = await this.context.Races.SingleAsync(x => x.Date.Year == year)
            };

            return View(viewModel);
        }

        [HttpGet("/results/{year}/list")]
        public async Task<IActionResult> List(int year)
        {
            var race = await this.context.Races
                .Include(x => x.RaceRunners)
                    .ThenInclude(x => x.Runner)
                .Include(x => x.RaceRunners)
                    .ThenInclude(x => x.AgeGroup)
                .FirstAsync(x => x.Date.Year == year);

            var runners = new List<RunnerViewModel>();

            foreach (var raceRunner in race.RaceRunners.OrderBy(x => x.Runner.Gender).ThenBy(x => x.Runner.LastName))
            {
                var runner = new RunnerViewModel
                {
                    Name = $"{raceRunner.Runner.FirstName} {raceRunner.Runner.LastName}",
                    Gender = raceRunner.Runner.Gender,
                    AgeGroupName = raceRunner.AgeGroup.Name
                };

                runners.Add(runner);
            }

            var viewModel = new ListViewModel
            {
                Race = race,
                Runners = runners
            };

            return View(viewModel);
        }

        [HttpGet("/results/{year}/overall")]
        public async Task<IActionResult> Overall(int year)
        {
            var race = await this.context.Races
                .Include(x => x.RaceRunners)
                    .ThenInclude(x => x.Runner)
                .Include(x => x.RaceRunners)
                    .ThenInclude(x => x.AgeGroup)
                .Include(x => x.Results)
                    .ThenInclude(x => x.Runner)
                .FirstAsync(x => x.Date.Year == year);

            
            var results = new List<ResultViewModel>();

            foreach (var dbResult in race.Results.OrderBy(x => x.OverallPlace))
            {
                var ageGroup = race.RaceRunners.First(x => x.RunnerId == dbResult.Runner.Id).AgeGroup;

                var result = new ResultViewModel
                {
                    Place = dbResult.OverallPlace,
                    Name = $"{dbResult.Runner.FirstName} {dbResult.Runner.LastName}",
                    Gender = dbResult.Runner.Gender,
                    AgeGroupName = ageGroup.Name,
                    Time = dbResult.Time,
                    RaceName = race.Name
                };

                results.Add(result);
            }

            var viewModel = new OverallViewModel
            {
                Race = race,
                Results = results
            };

            return View(viewModel);
        }

        [HttpGet("/results/{year}/age")]
        public async Task<IActionResult> AgeGroup(int year)
        {
            var race = await this.context.Races
                .Include(x => x.AgeGroups)
                    .ThenInclude(x => x.Results)
                .Include(x => x.RaceRunners)
                    .ThenInclude(x => x.Runner)
                .Include(x => x.RaceRunners)
                    .ThenInclude(x => x.AgeGroup)
                .Include(x => x.Results)
                    .ThenInclude(x => x.Runner)
                .FirstAsync(x => x.Date.Year == year);

            var ageGroups = new List<AgeGroupResultsViewModel>();

            foreach (var ageGroup in race.AgeGroups)
            {
                var raceRunnerIds = race.RaceRunners.Where(x => x.AgeGroup.Id == ageGroup.Id).Select(x => x.Runner.Id);
                var ageGroupResults = race.Results.Where(x => raceRunnerIds.Contains(x.Runner.Id));

                var results = new List<ResultViewModel>();

                foreach (var ageGroupResult in ageGroupResults)
                {
                    var res = new ResultViewModel
                    {
                        Place = ageGroupResult.AgeGroupPlace,
                        Name = $"{ageGroupResult.Runner.FirstName} {ageGroupResult.Runner.LastName}",
                        Gender = ageGroupResult.Runner.Gender,
                        AgeGroupName = ageGroup.Name,
                        Time = ageGroupResult.Time,
                        RaceName = race.Name
                    };

                    results.Add(res);
                }

                var result = new AgeGroupResultsViewModel
                {
                    Name = ageGroup.Name,
                    Gender = ageGroup.Gender,
                    Results = results.OrderBy(x => x.Place).ToList()
                };

                ageGroups.Add(result);
            }

            var viewModel = new AgeGroupViewModel
            {
                Race = race,
                AgeGroups = ageGroups.OrderBy(x => x.Gender).ThenBy(x => x.Name).ToList()
            };

            return View(viewModel);
        }
    }
}

LodiCornFest5k/Controllers/RunnersController.cs
using LodiCornFest5k.Data;
using LodiCornFest5k.ViewModels;
using LodiCornFest5k.ViewModels.Runners;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LodiCornFest5k.Controllers
{
    public class RunnersController : Controller
    {
        private readonly RaceContext context;

        public RunnersController(RaceContext context)
        {
            this.context = context;
        }

        [HttpGet("/runners/{runnerName}/index")]
        public async Task<IActionResult> RunnerDetails(string runnerName)
        {
            var names = runnerName.Split("-");
            var firstName = names[0];
            var lastName = names[1];

            var runner = await this.context.Runners
                .Include(x => x.Results)
                    .ThenInclude(x => x.Race)
                .Include(x => x.RaceRunners)
                    .ThenInclude(x => x.AgeGroup)
                .Include(x => x.RaceRunners)
                    .ThenInclude(x => x.Race)
                .FirstAsync(x => x.FirstName == firstName && x.LastName == lastName);

            var results = new List<ResultViewModel>();

            foreach (var dbResult in runner.Results.OrderBy(x => x.Race.Date))
            {
                var raceRunner = runner.RaceRunners.First(x => x.Race.Id == dbResult.Race.Id);

                var result = new ResultViewModel
                {
                    Name = $"{runner.FirstName} {runner.LastName}",
                    Gender = runner.Gender,
                    OverallPlace = dbResult.OverallPlace,
                    AgeGroupPlace = dbResult.AgeGroupPlace,
                    RaceName = dbResult.Race.Name,
                    Time = dbResult.Time,
                    AgeGroupName = raceRunner.AgeGroup.Name,
                    RaceYear = dbResult.Race.Date.Year
                };
                
                results.Add(result);
            }

            var viewModel = new RunnerDetailsViewModel
            {
                Runner = runner,
                Results = results
            };

            return View(viewModel);
        }
    }
}

LodiCornFest5k/Views/Results/AgeGroup.cshtml
@model LodiCornFest5k.ViewModels.Results.AgeGroupViewModel

@{
    ViewData["Title"] = $"{Model.Race.Name} Age Group Results";
}

@section Styles {
    <link rel="stylesheet" href="https://cdn.rawgit.com/afeld/bootstrap-toc/v1.0.0/dist/bootstrap-toc.min.css">
}

@section Scripts {
    <script src="https://cdn.rawgit.com/afeld/bootstrap-toc/v1.0.0/dist/bootstrap-toc.min.js"></script>
}

<div class="row">
    <div class="col-sm-2">
        <nav class="nav flex-column nav-pills">
            <span class="navbar-brand">@ViewData["Title"]</span>
            <a class="nav-link" is-active-route asp-controller="Results" asp-action="List" asp-route-year="@Model.Race.Date.Year">Runner List</a>
            <a class="nav-link" is-active-route asp-controller="Results" asp-action="Overall" asp-route-year="@Model.Race.Date.Year">Overall Results</a>
            <a class="nav-link" is-active-route asp-controller="Results" asp-action="AgeGroup" asp-route-year="@Model.Race.Date.Year">Results by Age Group</a>
        </nav>
    </div>
    <div class="col-sm-7">
        <h1>Age Group Results</h1>
        <h2>@Model.Race.Name</h2>

        @foreach (var ageGroup in Model.AgeGroups)
        {
            @if (ageGroup.Results.Any())
            {
                <h3 style="padding-top:4rem;">@ageGroup.Gender @ageGroup.Name</h3>
                <table class="table table-striped">
                    <caption>@ageGroup.Gender @ageGroup.Name Age Group Results of @Model.Race.Name</caption>
                    <thead class="thead-light">
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Gender</th>
                            <th>Age Group</th>
                            <th>Time</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var result in ageGroup.Results)
                        {
                            <tr>
                                <td>@result.Place</td>
                                <td>
                                    <a asp-controller="Runners" asp-action="RunnerDetails" asp-route-runnerName="@result.LinkName" target="_blank">@result.Name</a>
                                </td>
                                <td>@result.Gender</td>
                                <td>@result.AgeGroupName</td>
                                <td>@result.Time.ToString(@"mm\:ss\.ff")</td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
        }
    </div>
    <div class="col-sm-3 toc">
        <nav id="toc" data-toggle="toc">
        </nav>
    </div>
</div>

LodiCornFest5k/Views/Results/Index.cshtml
@model LodiCornFest5k.ViewModels.Results.IndexViewModel

@{
    ViewData["Title"] = "Results";
}

<h1>Race Results</h1>
<p>
    For each of the races below, select the <strong>Race Actions</strong> button to view the details.
</p>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Date</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var race in Model.Races)
        {
            <tr>
                <td>
                    @race.Name
                </td>
                <td>@race.Date.ToString("d")</td>
                <td class="text-center">
                    <div class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" id="RaceActionsButton-@race.Date.Year" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Race Actions
                        </button>
                        <div class="dropdown-menu" aria-labelledby="RaceActionsButton-@race.Id">
                            <a class="dropdown-item" asp-controller="Results" asp-action="List" asp-route-year="@race.Date.Year">Runner List</a>
                            <a class="dropdown-item" asp-controller="Results" asp-action="Overall" asp-route-year="@race.Date.Year">Overall Results</a>
                            <a class="dropdown-item" asp-controller="Results" asp-action="AgeGroup" asp-route-year="@race.Date.Year">Results by Age Group</a>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

LodiCornFest5k/Views/Results/List.cshtml
@model LodiCornFest5k.ViewModels.Results.ListViewModel

@{
    ViewData["Title"] = $"{Model.Race.Name} Runner List";
}

<div class="row">
    <div class="col-sm-2">
        <nav class="nav flex-column nav-pills">
            <span class="navbar-brand">@ViewData["Title"]</span>
            <a class="nav-link" is-active-route asp-controller="Results" asp-action="List" asp-route-year="@Model.Race.Date.Year">Runner List</a>
            <a class="nav-link" is-active-route asp-controller="Results" asp-action="Overall" asp-route-year="@Model.Race.Date.Year">Overall Results</a>
            <a class="nav-link" is-active-route asp-controller="Results" asp-action="AgeGroup" asp-route-year="@Model.Race.Date.Year">Results by Age Group</a>
        </nav>
    </div>
    <div class="col-sm-10">
        <h1>Runner List</h1>
        <h2>@Model.Race.Name</h2>

        <table class="table table-striped">
            <caption>Runner List of @Model.Race.Name</caption>
            <thead class="thead-light">
                <tr>
                    <th>Name</th>
                    <th>Gender</th>
                    <th>Age Group</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var runner in Model.Runners)
                {
                    <tr>
                        <td>
                            <a asp-controller="Runners" asp-action="RunnerDetails" asp-route-runnerName="@runner.LinkName" target="_blank">@runner.Name</a>
                        </td>
                        <td>@runner.Gender</td>
                        <td>@runner.AgeGroupName</td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

LodiCornFest5k/Views/Results/Overall.cshtml
@model LodiCornFest5k.ViewModels.Results.OverallViewModel

@{
    ViewData["Title"] = $"{Model.Race.Name} Overall Results";
}

<div class="row">
    <div class="col-sm-2">
        <nav class="nav flex-column nav-pills">
            <span class="navbar-brand">@ViewData["Title"]</span>
            <a class="nav-link" is-active-route asp-controller="Results" asp-action="List" asp-route-year="@Model.Race.Date.Year">Runner List</a>
            <a class="nav-link" is-active-route asp-controller="Results" asp-action="Overall" asp-route-year="@Model.Race.Date.Year">Overall Results</a>
            <a class="nav-link" is-active-route asp-controller="Results" asp-action="AgeGroup" asp-route-year="@Model.Race.Date.Year">Results by Age Group</a>
        </nav>
    </div>
    <div class="col-sm-10">
        <h1>Overall Results</h1>
        <h2>@Model.Race.Name</h2>

        <table class="table table-striped">
            <caption>Overall Results of @Model.Race.Name</caption>
            <thead class="thead-light">
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Gender</th>
                    <th>Age Group</th>
                    <th>Time</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var result in Model.Results)
                {
                    <tr>
                        <td>@result.Place</td>
                        <td>
                            <a asp-controller="Runners" asp-action="RunnerDetails" asp-route-runnerName="@result.LinkName" target="_blank">@result.Name</a>
                        </td>
                        <td>@result.Gender</td>
                        <td>@result.AgeGroupName</td>
                        <td>@result.Time.ToString(@"mm\:ss\.ff")</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

LodiCornFest5k/Views/Results/Race.cshtml
@model LodiCornFest5k.ViewModels.Results.RaceViewModel

@{
    ViewData["Title"] = $"{Model.Race.Name} Results";
}

<h1>Race Results</h1>
<h2>@Model.Race.Name</h2>